### PR TITLE
Mondrian zoom

### PR DESCRIPTION
**Pull request by tangentstorm**
I have large diagrams that are painful to zoom with the action buttons.

This patch allows zooming the live view more quickly with the mouse wheel.

### CODE REVIEW

**Comment by seandenigris** [comment]
This sounds like a cool enhancement! I've had similar experiences

**Comment by JurajKubelka** [comment]
Hi @tangentstorm, thank you for the contribution. It is a great enhancement. Can you sign the [Contributor License Agreement](https://gtoolkit.com/community/cla?gitHublogin=tangentstorm)? When it is done, I will merge the pull request. 

-- Juraj

**Comment by tangentstorm** [comment]
Thanks Juraj!

FYI, that form appears to be broken. It looks like it's trying to do a
mailto: link but none of my browsers even try to respond to it.
I copied and pasted the HTML into Gmail and manually sent it just now.
Hopefully that works?

**Comment by JurajKubelka** [comment]
@tangentstorm: I confirm we received the our CLA and I am going to merge the pull request. 

Thank you for the CLA bug report. We will improve it.

**Comment by girba** [comment]
Mapping the zoom on scroll does not work well with visualizations embedded in Lepiter. primary+scroll would work better. We also would benefit from zooming through pinching on a trackpad

**Pull request merged**
