### PR TITLE
Making mouse wheel scroll shortcut zoom proportionally instead of using a constant value that's too small when zoomed in and too big when zoomed out.

### PR DESCRIPTION
**Pull request by botwhytho**

### CODE REVIEW

**Comment by botwhytho** [comment]
Before:

https://github.com/feenkcom/gtoolkit-visualizer/assets/21220773/aba874fb-3d2b-4325-8e06-a9f8ac8154fe

After:


https://github.com/feenkcom/gtoolkit-visualizer/assets/21220773/fddaea18-296d-4dc9-a447-6b3d0156a9d5

**Comment by girba** [comment]
Very cool!

**Review by syrel — COMMENTED** [review]
Looks good

**Comment by svenvc** [comment]
Thank you !

**Pull request merged**
